name: Trigger clair db image build

# This workflow creates/reopens PR and closes it
# in order to trigger PAC to build clair DB image

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  SOURCE_BRANCH: main # building from main

jobs:
  test:
    name: Build the new image
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        ref: 'main'
    - name: Run Clair-Action to update DB
      uses: docker://quay.io/projectquay/clair-action:v0.0.11@sha256:80486643baad47f2ac606e5c0e5274f296c08464aebb3dc90f97f22ba92505dd
      with:
        args: update --level info
      env:
        DB_PATH: /tmp/matcher.db
    - name: Download DB from container to runner
      run: |
        container_id=$(docker ps -lq)
        docker cp $container_id:/tmp/matcher.db ./clair-db/matcher.db

        ls -la ./clair-db/matcher.db
        file ./clair-db/matcher.db || exit 1
    - name: Commit and push if changed
      run: |
        git config --global user.email "<>"
        git config --global user.name "daily-build-trigger"

        git add ./clair-db/matcher.db
        if ! git diff --staged --quiet; then
          git commit -m "chore: update Clair DB snapshot $(date -u +'%Y-%m-%d')"
          git push
          echo "✅ Database updated and pushed."
        else
          echo "ℹ️  Database is up-to-date. No changes to commit."
        fi